[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "climusic"
version = "0.1.0"
description = "A feature-rich terminal YouTube Music player."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ytmusicapi",
    "yt-dlp"
]

[project.scripts]
# This creates the terminal command 'ytmusic'
ytmusic = "yt_music_cli.main:main"
